/**
 * Moments
 * string
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@launchnotes.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostMomentsProjectIdIngest422Response {
    'errors'?: Array<string>;
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PostMomentsProjectIdIngest422Response.attributeTypeMap;
    }
}

