/**
 * Moments
 * string
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@launchnotes.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostMomentsProjectIdIngestRequest {
    /**
    * Object that is supposed to look like the schema specified.
    */
    'data': object;
    'projectId': string;
    /**
    * Path to a schema to specify what the payload is supposed to look like.
    */
    'schemaId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "schemaId",
            "baseName": "schemaId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PostMomentsProjectIdIngestRequest.attributeTypeMap;
    }
}

