/**
 * Moments
 * string
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@launchnotes.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PostMomentsProjectIdIngest200Response {
    'momentId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "momentId",
            "baseName": "momentId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PostMomentsProjectIdIngest200Response.attributeTypeMap;
    }
}

